validate the input

diff --git a/.github/workflows/packer_build.yml b/.github/workflows/packer_build.yml
--- a/.github/workflows/packer_build.yml
+++ b/.github/workflows/packer_build.yml
@@ -45,8 +45,13 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
       
-      #- name: Setup Terraform
-      #  uses: hashicorp/setup-terraform@v1
+      - name: Verify Input
+        run: |
+          if [[ "${{ github.event.inputs.action }}" != "apply" && "${{ github.event.inputs.action }}" != "destroy" ]]; then
+            echo "Invalid input: ${{ github.event.inputs.action }}. Please select 'apply' or 'destroy'."
+            exit 1
+          fi
+        shell: bash
         
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
